version: "2.1"
services:
  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/mods:healthchecks-apprise
      - SITE_ROOT=https://healthchecks.p.lan.frostwolf.io
      - SITE_NAME=Healthchecks
      - DEFAULT_FROM_EMAIL=no-reply@starstreak.net
      - EMAIL_HOST=mailgun-relay
      - EMAIL_PORT=587
      - EMAIL_USE_TLS=True
      - ALLOWED_HOSTS=["*"]
      - USE_PAYMENTS=False
      - REGISTRATION_OPEN=False
      
    networks:
      - traefik-proxy
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.healthchecks.entrypoints=http"
      - "traefik.http.routers.healthchecks.rule=Host(`healthchecks.p.lan.frostwolf.io`)"
      - "traefik.http.routers.healthchecks.middlewares=healthchecks-https-redirect"
      - "traefik.http.middlewares.healthchecks-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.healthchecks-secure.entrypoints=https"
      - "traefik.http.routers.healthchecks-secure.rule=Host(`healthchecks.p.lan.frostwolf.io`)"
      - "traefik.http.routers.healthchecks-secure.tls=true"
      - "traefik.http.routers.healthchecks-secure.service=healthchecks-svc"
      - "traefik.http.services.healthchecks-svc.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true

volumes:
  config:
