version: "2.1"
services:
  tautulli:
    image: linuxserver/tautulli:version-v2.7.2
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - traefik-proxy
      - egress
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=http"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.p.lan.starstreak.net`)"
      - "traefik.http.routers.tautulli.middlewares=tautulli-https-redirect"
      - "traefik.http.middlewares.tautulli-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tautulli-secure.entrypoints=https"
      - "traefik.http.routers.tautulli-secure.rule=Host(`tautulli.p.lan.starstreak.net`)"
      - "traefik.http.routers.tautulli-secure.tls=true"
      - "traefik.http.routers.tautulli-secure.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
  egress:
    external: true

volumes:
  config:
