version: '3.7'

services:
  traefik-certs-dumper:
    container_name: traefik-certs-dumper
    image: ldez/traefik-certs-dumper:v2.7.4
    network_mode: none
    restart: unless-stopped
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /letsencrypt/acme.json ]
        || ! [ `jq ".cloudflare.Certificates | length" /letsencrypt/acme.json` != 0 ]; do
          sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
        --source /letsencrypt/acme.json --dest /certs'
    volumes:
      - letsencrypt_json:/letsencrypt
      - letsencrypt_certs:/certs

volumes:
  letsencrypt_json:
    external: true
  letsencrypt_certs:
    external: true
