version: "3.7"

services:
  sui:
    container_name: sui
    restart: unless-stopped
    image: willfantom/sui:dev
    networks:
      - traefik-proxy
    volumes:
      - ./configs:/sui
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - SUI_DEBUG=true
    labels:
      - sui.enabled=true
      - sui.icon=home
      - "traefik.enable=true"
      - "traefik.http.routers.sui.entrypoints=http"
      - "traefik.http.routers.sui.rule=Host(`sui.p.lan.frostwolf.io`)"
      - "traefik.http.routers.sui.middlewares=sui-https-redirect"
      - "traefik.http.middlewares.sui-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sui-secure.entrypoints=https"
      - "traefik.http.routers.sui-secure.rule=Host(`sui.p.lan.frostwolf.io`)"
      - "traefik.http.routers.sui-secure.tls=true"
      - "traefik.http.routers.sui-secure.service=sui-svc"
      - "traefik.http.services.sui-svc.loadbalancer.server.port=6999"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
