version: 3

services:
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    networks:
      - traefik-proxy
    volumes:
      - ./config:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

networks:
  traefik-proxy:
    external: true
