version: "2.1"
services:
  radarr-uhd:
    image: linuxserver/radarr
    container_name: radarr-uhd
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    networks:
      - traefik-proxy
      - nzbget
    volumes:
      - config:/config
      - /mnt/zstorage/media/movies-uhd:/mnt/media/movies-uhd
      - downloads:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-uhd.entrypoints=http"
      - "traefik.http.routers.radarr-uhd.rule=Host(`radarr-uhd.p.lan.frostwolf.io`)"
      - "traefik.http.routers.radarr-uhd.middlewares=radarr-uhd-https-redirect"
      - "traefik.http.middlewares.radarr-uhd-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr-uhd-secure.entrypoints=https"
      - "traefik.http.routers.radarr-uhd-secure.rule=Host(`radarr-uhd.p.lan.frostwolf.io`)"
      - "traefik.http.routers.radarr-uhd-secure.tls=true"
      - "traefik.http.routers.radarr-uhd-secure.service=radarr-uhd-svc"
      - "traefik.http.services.radarr-uhd-svc.loadbalancer.server.port=7878"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
  nzbget:
    external: true

volumes:
  config:
  downloads:
    external: true
