version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - egress
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - data:/prometheus
    command: --web.enable-lifecycle --web.enable-admin-api --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

networks:
  egress:
    external: true

volumes:
  data: 
