[http.routers]
   # Define a connection between requests and services
     [http.routers.tvheadend]
        rule = "Host(`tvheadend.p.lan.starstreak.net`)"
        entrypoints = ["https"]
        service = "tvheadend"
     [http.routers.tvheadend.tls]
        certResolver = "cloudflare"

 [http.services]
        # Define how to reach an existing service on our infrastructure
        [http.services.tvheadend.loadBalancer]
           [[http.services.tvheadend.loadBalancer.servers]]
             url = "http://10.1.10.98:9981"

