version: "2.1"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    networks:
      - traefik-proxy
    volumes:
      - config:/opt/adguardhome/conf
      - work:/opt/adguardhome/work
      - letsencrypt_certs:/certs
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.entrypoints=http"
      - "traefik.http.routers.adguard.rule=Host(`adguard.p.lan.starstreak.net`)"
      - "traefik.http.routers.adguard.middlewares=adguard-https-redirect"
      - "traefik.http.middlewares.adguard-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.adguard-secure.entrypoints=https"
      - "traefik.http.routers.adguard-secure.rule=Host(`adguard.p.lan.starstreak.net`)"
      - "traefik.http.routers.adguard-secure.tls=true"
      - "traefik.http.routers.adguard-secure.service=adguard-svc"
      - "traefik.http.services.adguard-svc.loadbalancer.server.port=80"
        #      - "traefik.http.services.adguard-svc.loadbalancer.server.scheme=https"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true

volumes:
  config:
  work:
  letsencrypt_certs:
    external: true
