version: "2.1"
services:
  nzbget:
    image: linuxserver/nzbget:amd64-version-v21.0
    container_name: nzbget
    environment:
      - PUID=2000
      - PGID=2000
      - TZ=Europe/London
    networks:
      - traefik-proxy
      - nzbget
      - vpn
    volumes:
      - config:/config
      - downloads:/downloads
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=http"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.p.lan.starstreak.net`)"
      - "traefik.http.routers.nzbget.middlewares=nzbget-https-redirect"
      - "traefik.http.middlewares.nzbget-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nzbget-secure.entrypoints=https"
      - "traefik.http.routers.nzbget-secure.rule=Host(`nzbget.p.lan.starstreak.net`)"
      - "traefik.http.routers.nzbget-secure.tls=true"
      - "traefik.http.routers.nzbget-secure.service=nzbget-svc"
      - "traefik.http.services.nzbget-svc.loadbalancer.server.port=6789"
      - "traefik.docker.network=traefik-proxy"

networks:
  traefik-proxy:
    external: true
  nzbget:
    external: true
  vpn:
    external:
      name: mullvad-vpn

volumes:
  config:
  downloads:
    external: true
