version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce:2.19.0 
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik-proxy
      - egress
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.p.lan.starstreak.net`)"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.p.lan.starstreak.net`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer-svc"
      - "traefik.http.services.portainer-svc.loadbalancer.server.port=9000"
      - "traefik.docker.network=traefik-proxy"

volumes:
  portainer_data:

networks:
  traefik-proxy:
    external: true
  egress:
    external: true
