version: '2.2'
services:
  unifi-controller:
    container_name: "unifi-controller"
    image: "linuxserver/unifi-controller"
    networks:
      - traefik-proxy
      - egress
    restart: unless-stopped
    volumes:
      - config:/config
    environment:
      - PGID=1000
      - PUID=1000
      - MEM_LIMIT=1024M
    ports:
      - 1900:1900/udp
      - 3478:3478/udp # STUN
      - 5514:5514/tcp
      - 6789:6789/tcp # Speed test
      - 8080:8080/tcp # Device/ controller comm.
      - 8443:8443/tcp
      - 10001:10001/udp # AP discovery
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.entrypoints=http"
      - "traefik.http.routers.unifi.rule=Host(`unifi.p.lan.starstreak.net`)"
      - "traefik.http.routers.unifi.middlewares=unifi-https-redirect"
      - "traefik.http.middlewares.unifi-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.unifi-secure.entrypoints=https"
      - "traefik.http.routers.unifi-secure.rule=Host(`unifi.p.lan.starstreak.net`)"
      - "traefik.http.routers.unifi-secure.tls=true"
      - "traefik.http.routers.unifi-secure.service=unifi-svc"
      - "traefik.http.services.unifi-svc.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi-svc.loadbalancer.server.scheme=https"
      - "traefik.docker.network=traefik-proxy"

volumes:
  config:

networks:
  traefik-proxy:
    external: true
  egress:
    external: true
